# Generated by Django 5.2 on 2025-06-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalias', '0002_anomalia_observacoes_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalia',
            name='data_resolvida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
