# Generated by Django 5.2 on 2025-06-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalias', '0003_anomalia_data_resolvida'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalia',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
