# Generated by Django 5.2 on 2025-06-26 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalias', '0004_anomalia_ativo'),
        ('computadores', '0001_initial'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalia',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salas.sala'),
        ),
        migrations.AddField(
            model_name='anomalia',
            name='tipo',
            field=models.CharField(blank=True, choices=[('MOBILARIO', 'Mobiliário'), ('SALA', 'Problema na Sala'), ('LIMPEZA', 'Limpeza'), ('PROJETOR', 'Projetor com Problema'), ('ACESSO', 'Acesso Restrito ou Trancado'), ('REDE', 'Rede ou Internet'), ('OUTRO', 'Outro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='anomalia',
            name='computador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='computadores.computador'),
        ),
    ]
