# Generated by Django 5.2 on 2025-06-27 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anomalias', '0005_anomalia_sala_anomalia_tipo_and_more'),
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalia',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalias', to='salas.sala'),
        ),
    ]
