# Generated by Django 5.2 on 2026-01-26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("anomalias", "0006_alter_anomalia_sala"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnexoAnomalia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("arquivo", models.FileField(upload_to="anomalias/anexos/")),
                ("tipo", models.CharField(choices=[("IMAGEM", "Imagem"), ("VIDEO", "Video")], max_length=10)),
                ("data_upload", models.DateTimeField(auto_now_add=True)),
                ("anomalia", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="anexos", to="anomalias.anomalia")),
            ],
        ),
    ]
