# Generated by Django 5.2 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomalias", "0007_anexo_anomalia"),
    ]

    operations = [
        migrations.AddField(
            model_name="anomalia",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("CRITICA", "Crítica"),
                    ("ALTA", "Alta"),
                    ("MEDIA", "Média"),
                    ("BAIXA", "Baixa"),
                ],
                default="MEDIA",
                max_length=10,
            ),
        ),
    ]
