# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anomalias", "0008_anomalia_prioridade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PROF", "Professor"),
                    ("COORD", "Coordenador"),
                    ("ADMIN", "Administrador"),
                    ("TEC", "Técnico"),
                ],
                max_length=10,
            ),
        ),
    ]
